name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Test
        run: |
          sudo apt-get install -y libboost-all-dev lcov
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON ..
          make && make CTEST_OUTPUT_ON_FAILURE=1 test
      - name: Coverage
        run: |
          lcov -c -d . -o coverage --include "*/include/telegraph/*"
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
