name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Test
        run: |
          sudo apt-get install -y libboost-all-dev lcov
          mkdir -p build && cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DTELEGRAPH_ENABLE_TESTS=ON ..
          make && make CTEST_OUTPUT_ON_FAILURE=1 test
      - name: Coverage
        run: |
          lcov -c -d . -o coverage --include "*/include/telegraph/*"
          bash <(curl -s https://codecov.io/bash) -f coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Benchmarks
        run: |
          mkdir -p build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DTELEGRAPH_ENABLE_TESTS=OFF -DTELEGRAPH_ENABLE_BENCHMARKS=ON ..
          make && ./benchmarks/benchmarks | tee output.txt
