on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build Doxygen documentation
        uses: mattnotmitt/doxygen-action@v1.3.1
        with:
          enable-latex: true
